# Example Swarm demo stack (whoami)
# This file is a TEMPLATE. Replace placeholder values (UID:GID, ./data, ports) before using it
# in a real environment. It is intended for lab/demo usage.

version: "3.9"  # Compose file format version compatible with Docker Swarm stack deploy

services:
  whoami:        # Logical service name inside the stack
    image: traefik/whoami  # Tiny HTTP service that returns request/host information
    deploy:
      replicas: 1          # Number of tasks/containers in the Swarm service
      # You can add more deploy options here:
      # restart_policy, placement constraints, resource limits, etc.
    ports:
      - "8000:80"          # Publish container port 80 on host port 8000 (nodePort-style)
    user: "UID:GID"        # Run the container as a specific UID:GID (replace with real values)
    volumes:
      - ./data:/data       # Bind-mount local ./data into /data inside the container
                           # In real Swarm stacks this is typically replaced with an NFS path